version: '3.9'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hetic-learning-go
      MYSQL_USER: hetic
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

volumes:
    mysql: